#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DailyLifeHelper.Droid.Resource", IsApplication=true)]

namespace DailyLifeHelper.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::DailyLifeHelper.Droid.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::DailyLifeHelper.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::DailyLifeHelper.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::DailyLifeHelper.Droid.Resource.String.Hello;
			global::Plugin.TextToSpeech.Resource.String.ApplicationName = global::DailyLifeHelper.Droid.Resource.String.ApplicationName;
			global::Plugin.TextToSpeech.Resource.String.Hello = global::DailyLifeHelper.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Developing = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int google_speech = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int google_text = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int google_trans = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int GPS1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int GPS2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int loginbg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int navigation = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int photo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int photo_CHN = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int selectlang = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int todo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int weather = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int weather_forecast = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
